[config]
exclude-merge-commit=false
check-summary-length=false

[matchers]
all="**"

[examples]
a_new_feature="""
feat(module) : An added feature

New feature
"""
a_refactor="""
ref(module) : Refactor module

Refactor a module
"""

an_update="""
update(module) : Update a file

Update file
"""
